### ISSUE TITLE
Actually perform type-checking and type-driven compilation in the C frontend

### ISSUE THREAD

**Issue by bmourad01** [draperlaboratory/VIBES#164]
There are some operators in the C frontend that will fail to compile without explicit casts. Furthermore, no real type-checking is done of the C code in input (to be fair, the typing rules of C are not trivial). It would be nice to actually implement these typing rules and then use the type information to generate better code.

**Comment by codyroux** [comment]
Agreed, though IMHO, the implicit type casts/promotions are so error-prone from the user-end that my tentative thought was to have them explicit rather than implicit.

But if you want the actual C semantics, at least this part is pretty well-defined for the compiler writer.

Not sure what other difficulties there are, at least until you allow qualifiers.
